package zorxauth

/*
	groupPolicy.go

	This file handle group policy for zorxauth,
	it will be used to determine which group access policy
	a user belongs to, and what permissions they have.

	Group policies are stored as JSON files in the config folder
	but user data stores in db only due to the password hash
*/

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"imuslab.com/zoraxy/mod/utils"
)

const (
	GROUP_POLICY_FOLDER   = "group_policies"
	GROUP_POLICY_FILE_EXT = ".json"
)

// GroupPolicy defines a group-level access policy that can be shared across users
type GroupPolicy struct {
	ID           string   `json:"id"`           //Group ID, generated by uuid, used for internal reference
	Name         string   `json:"name"`         //Group name, used for display and reference
	Description  string   `json:"description"`  //Group description, used for display and reference
	AllowedHosts []string `json:"allowedHosts"` //List of allowed hosts for this group, if empty, allow all hosts
}

// initGroupPolicyStore ensures the storage folder exists and loads policies from disk into sync.Map
func (ar *AuthRouter) initGroupPolicyStore() {
	// Ensure the storage folder exists
	folder := ar.groupPolicyFolder()
	if err := os.MkdirAll(folder, 0755); err != nil {
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to create group policy folder: "+err.Error(), err)
		}
		return
	}

	ar.loadGroupPoliciesFromDisk()
}

// groupPolicyFolder returns the absolute path to the group policy storage folder
func (ar *AuthRouter) groupPolicyFolder() string {
	base := ar.Options.ConfigFolderPath
	if base == "" {
		base = defaultConfigFolderPath
	}
	return filepath.Join(base, GROUP_POLICY_FOLDER)
}

// migrateLegacyGroupPolicyFolder moves legacy group policy files from the old
// relative ./conf path into the configured config folder when possible.
func (ar *AuthRouter) migrateLegacyGroupPolicyFolder(targetBase string) {
	sourceFolder := filepath.Clean(filepath.Join(defaultConfigFolderPath, GROUP_POLICY_FOLDER))
	targetFolder := filepath.Clean(filepath.Join(targetBase, GROUP_POLICY_FOLDER))

	if sourceFolder == targetFolder {
		return
	}

	entries, err := os.ReadDir(sourceFolder)
	if err != nil {
		if !os.IsNotExist(err) && ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to inspect legacy group policy folder: "+err.Error(), err)
		}
		return
	}

	groupPolicyFiles := []os.DirEntry{}
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), GROUP_POLICY_FILE_EXT) {
			groupPolicyFiles = append(groupPolicyFiles, entry)
		}
	}

	if len(groupPolicyFiles) == 0 {
		return
	}

	if err := os.MkdirAll(filepath.Dir(targetFolder), 0755); err != nil {
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to prepare target group policy folder: "+err.Error(), err)
		}
		return
	}

	if _, err := os.Stat(targetFolder); os.IsNotExist(err) {
		if err := os.Rename(sourceFolder, targetFolder); err == nil {
			if ar.Logger != nil {
				ar.Logger.PrintAndLog("zorxauth", "Migrated legacy group policies to "+targetFolder, nil)
			}
			return
		}
	}

	if err := os.MkdirAll(targetFolder, 0755); err != nil {
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to create target group policy folder: "+err.Error(), err)
		}
		return
	}

	copied := 0
	skipped := 0
	for _, entry := range groupPolicyFiles {
		sourceFile := filepath.Join(sourceFolder, entry.Name())
		targetFile := filepath.Join(targetFolder, entry.Name())

		if _, err := os.Stat(targetFile); err == nil {
			skipped++
			continue
		}

		data, err := os.ReadFile(sourceFile)
		if err != nil {
			if ar.Logger != nil {
				ar.Logger.PrintAndLog("zorxauth", "Failed to read legacy group policy file "+entry.Name()+": "+err.Error(), err)
			}
			continue
		}

		if err := os.WriteFile(targetFile, data, 0644); err != nil {
			if ar.Logger != nil {
				ar.Logger.PrintAndLog("zorxauth", "Failed to copy legacy group policy file "+entry.Name()+": "+err.Error(), err)
			}
			continue
		}

		copied++
	}

	if ar.Logger != nil && (copied > 0 || skipped > 0) {
		ar.Logger.PrintAndLog("zorxauth", fmt.Sprintf("Migrated %d legacy group policy files to %s (%d skipped)", copied, targetFolder, skipped), nil)
	}
}

// groupPolicyFilePath returns the file path for a given group policy ID
func (ar *AuthRouter) groupPolicyFilePath(id string) string {
	return filepath.Join(ar.groupPolicyFolder(), id+GROUP_POLICY_FILE_EXT)
}

// loadGroupPoliciesFromDisk reads all .json files from the policy folder into the sync.Map
func (ar *AuthRouter) loadGroupPoliciesFromDisk() {
	folder := ar.groupPolicyFolder()
	entries, err := os.ReadDir(folder)
	if err != nil {
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to read group policy folder: "+err.Error(), err)
		}
		return
	}

	loaded := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), GROUP_POLICY_FILE_EXT) {
			continue
		}

		data, err := os.ReadFile(filepath.Join(folder, entry.Name()))
		if err != nil {
			if ar.Logger != nil {
				ar.Logger.PrintAndLog("zorxauth", "Failed to read group policy file "+entry.Name()+": "+err.Error(), err)
			}
			continue
		}

		var gp GroupPolicy
		if err := json.Unmarshal(data, &gp); err != nil {
			if ar.Logger != nil {
				ar.Logger.PrintAndLog("zorxauth", "Failed to parse group policy file "+entry.Name()+": "+err.Error(), err)
			}
			continue
		}

		if gp.ID == "" {
			continue
		}

		ar.groupPolicies.Store(gp.ID, &gp)
		loaded++
	}

	if ar.Logger != nil {
		ar.Logger.PrintAndLog("zorxauth", "Loaded "+strconv.Itoa(loaded)+" group policies from disk", nil)
	}
}

// saveGroupPolicyToDisk writes a single group policy to its JSON file
func (ar *AuthRouter) saveGroupPolicyToDisk(gp *GroupPolicy) error {
	folder := ar.groupPolicyFolder()
	if err := os.MkdirAll(folder, 0755); err != nil {
		return err
	}

	data, err := json.MarshalIndent(gp, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(ar.groupPolicyFilePath(gp.ID), data, 0644)
}

// deleteGroupPolicyFromDisk removes the JSON file for a group policy
func (ar *AuthRouter) deleteGroupPolicyFromDisk(id string) error {
	fp := ar.groupPolicyFilePath(id)
	if _, err := os.Stat(fp); os.IsNotExist(err) {
		return nil // already gone
	}
	return os.Remove(fp)
}

// GetGroupPolicyByID returns a copy of the group policy with the given ID
func (ar *AuthRouter) GetGroupPolicyByID(id string) (*GroupPolicy, error) {
	val, exists := ar.groupPolicies.Load(id)
	if !exists {
		return nil, errors.New("group policy not found")
	}

	gp, ok := val.(*GroupPolicy)
	if !ok {
		return nil, errors.New("invalid group policy entry")
	}

	// Return a copy to avoid race conditions on the slice
	gpCopy := *gp
	gpCopy.AllowedHosts = make([]string, len(gp.AllowedHosts))
	copy(gpCopy.AllowedHosts, gp.AllowedHosts)
	return &gpCopy, nil
}

// ListGroupPolicies returns all group policies sorted by name
func (ar *AuthRouter) ListGroupPolicies() []*GroupPolicy {
	var result []*GroupPolicy
	ar.groupPolicies.Range(func(key, value interface{}) bool {
		gp, ok := value.(*GroupPolicy)
		if !ok {
			return true
		}
		gpCopy := *gp
		gpCopy.AllowedHosts = make([]string, len(gp.AllowedHosts))
		copy(gpCopy.AllowedHosts, gp.AllowedHosts)
		result = append(result, &gpCopy)
		return true
	})

	sort.Slice(result, func(i, j int) bool {
		return strings.ToLower(result[i].Name) < strings.ToLower(result[j].Name)
	})

	return result
}

// GetAllowedHostsForUser resolves the effective allowed hosts for a user.
// If UseGroupPolicy is true and GroupID is set, it uses the group policy's AllowedHosts.
// Otherwise, it falls back to the user's own AllowedHosts.
func (ar *AuthRouter) GetAllowedHostsForUser(user *User) []string {
	if user.UseGroupPolicy && user.GroupID != "" {
		gp, err := ar.GetGroupPolicyByID(user.GroupID)
		if err == nil {
			return gp.AllowedHosts
		}
		// If group policy not found, log a warning and fall back to user's own hosts
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Group policy "+user.GroupID+" not found for user "+user.Username+", falling back to user-level hosts", nil)
		}
	}
	return user.AllowedHosts
}

/* ===================== HTTP API Handlers ===================== */

// HandleGroupPolicyList returns all group policies as JSON (GET)
func (ar *AuthRouter) HandleGroupPolicyList(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		utils.SendErrorResponse(w, "method not allowed")
		return
	}

	policies := ar.ListGroupPolicies()
	js, _ := json.Marshal(policies)
	utils.SendJSONResponse(w, string(js))
}

// HandleGroupPolicyCreate creates a new group policy (POST)
func (ar *AuthRouter) HandleGroupPolicyCreate(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		utils.SendErrorResponse(w, "method not allowed")
		return
	}

	name, err := utils.PostPara(r, "name")
	if err != nil || strings.TrimSpace(name) == "" {
		utils.SendErrorResponse(w, "group policy name is required")
		return
	}

	description := strings.TrimSpace(r.FormValue("description"))
	allowedHosts := normalizeAllowedHosts(r.FormValue("allowedHosts"))

	gp := &GroupPolicy{
		ID:           uuid.NewString(),
		Name:         strings.TrimSpace(name),
		Description:  description,
		AllowedHosts: allowedHosts,
	}

	ar.groupPolicies.Store(gp.ID, gp)

	if err := ar.saveGroupPolicyToDisk(gp); err != nil {
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to save group policy to disk: "+err.Error(), err)
		}
		utils.SendErrorResponse(w, "failed to persist group policy")
		return
	}

	utils.SendOK(w)
}

// HandleGroupPolicyUpdate updates an existing group policy (POST)
func (ar *AuthRouter) HandleGroupPolicyUpdate(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		utils.SendErrorResponse(w, "method not allowed")
		return
	}

	id, err := utils.PostPara(r, "id")
	if err != nil || strings.TrimSpace(id) == "" {
		utils.SendErrorResponse(w, "group policy ID is required")
		return
	}

	val, exists := ar.groupPolicies.Load(id)
	if !exists {
		utils.SendErrorResponse(w, "group policy not found")
		return
	}

	oldGP, ok := val.(*GroupPolicy)
	if !ok {
		utils.SendErrorResponse(w, "invalid group policy entry")
		return
	}

	// Build an updated copy so readers of the old pointer are not affected
	updated := *oldGP
	updated.AllowedHosts = make([]string, len(oldGP.AllowedHosts))
	copy(updated.AllowedHosts, oldGP.AllowedHosts)

	if name := strings.TrimSpace(r.FormValue("name")); name != "" {
		updated.Name = name
	}

	if _, ok := r.Form["description"]; ok {
		updated.Description = strings.TrimSpace(r.FormValue("description"))
	}

	if _, ok := r.Form["allowedHosts"]; ok {
		updated.AllowedHosts = normalizeAllowedHosts(r.FormValue("allowedHosts"))
	}

	ar.groupPolicies.Store(id, &updated)

	if err := ar.saveGroupPolicyToDisk(&updated); err != nil {
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to save group policy to disk: "+err.Error(), err)
		}
		utils.SendErrorResponse(w, "failed to persist group policy")
		return
	}

	utils.SendOK(w)
}

// HandleGroupPolicyDelete deletes a group policy (POST)
func (ar *AuthRouter) HandleGroupPolicyDelete(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		utils.SendErrorResponse(w, "method not allowed")
		return
	}

	id, err := utils.PostPara(r, "id")
	if err != nil || strings.TrimSpace(id) == "" {
		utils.SendErrorResponse(w, "group policy ID is required")
		return
	}

	if _, exists := ar.groupPolicies.Load(id); !exists {
		utils.SendErrorResponse(w, "group policy not found")
		return
	}

	ar.groupPolicies.Delete(id)

	if err := ar.deleteGroupPolicyFromDisk(id); err != nil {
		if ar.Logger != nil {
			ar.Logger.PrintAndLog("zorxauth", "Failed to delete group policy file: "+err.Error(), err)
		}
	}

	// Unassign all users that reference this group policy
	users, err := ar.listUsers()
	if err == nil {
		for _, user := range users {
			if user.UseGroupPolicy && strings.EqualFold(user.GroupID, id) {
				user.UseGroupPolicy = false
				user.GroupID = ""
				if saveErr := ar.saveUser(user, ""); saveErr != nil {
					if ar.Logger != nil {
						ar.Logger.PrintAndLog("zorxauth", "Failed to unassign group policy from user "+user.Username+": "+saveErr.Error(), saveErr)
					}
				}
			}
		}
	}

	utils.SendOK(w)
}
