package statistic

import (
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/microcosm-cc/bluemonday"
	"imuslab.com/zoraxy/mod/database"
)

/*
	Statistic Package

	This packet is designed to collection information
	and store them for future analysis
*/

// Faststat, a interval summary for all collected data and avoid
// looping through every data everytime a overview is needed
type DailySummary struct {
	TotalRequest int64 //Total request of the day
	ErrorRequest int64 //Invalid request of the day, including error or not found
	ValidRequest int64 //Valid request of the day
	//Type counters
	ForwardTypes        *sync.Map //Map that hold the forward types
	RequestOrigin       *sync.Map //Map that hold [country ISO code]: visitor counter
	RequestClientIp     *sync.Map //Map that hold all unique request IPs
	Referer             *sync.Map //Map that store where the user was refered from
	UserAgent           *sync.Map //Map that store the useragent of the request
	RequestURL          *sync.Map //Request URL of the request object
	RequestMethods      *sync.Map //Map that hold the HTTP methods (GET / POST / ...) of the requests
	DownstreamHostnames *sync.Map //Request count of downstream hostname
	UpstreamHostnames   *sync.Map //Forwarded request count of upstream hostname

	// bounded tracks the logical size of each map above and serializes
	// the trim path so that high-cardinality request inputs (many unique
	// IPs, UA/Referer strings, or URL paths) don't grow the maps without
	// bound when the cap is enabled.
	bounded boundedCounters
}

type RequestInfo struct {
	IpAddr                        string //IP address of the downstream request
	RequestOriginalCountryISOCode string //ISO code of the country where the request originated
	Succ                          bool   //If the request is successful and resp generated by upstream instead of Zoraxy (except static web server)
	StatusCode                    int    //HTTP status code of the request
	ForwardType                   string //Forward type of the request, usually the proxy type (e.g. host-http, subdomain-websocket or vdir-http or any of the combination)
	RequestMethod                 string //HTTP method of the downstream request (e.g. GET, POST)
	Referer                       string //Referer of the downstream request
	UserAgent                     string //UserAgent of the downstream request
	RequestURL                    string //Request URL
	Target                        string //Target domain or hostname
	Upstream                      string ////Upstream domain or hostname, if the request is forwarded to upstream
}

type CollectorOption struct {
	Database *database.Database
	// MaxEntriesPerStatMap is the per-dimension soft cap for the sync.Map
	// fields in DailySummary. 0 means unbounded (matches upstream behavior
	// byte-for-byte). A positive value enables a bounded mode where, when
	// the cap is exceeded, the entries with the lowest request counts are
	// dropped first (see mod/statistic/bounded.go). Recommended value when
	// enabled: 20000 (≈32MB worst-case across all 8 maps).
	MaxEntriesPerStatMap int
}

type Collector struct {
	rtdataStopChan chan bool
	autoSaveTicker *time.Ticker
	autSaveStop    chan bool
	DailySummary   *DailySummary
	Option         *CollectorOption
	// incr is the per-request map-increment strategy, chosen once at startup
	// based on Option.MaxEntriesPerStatMap. See newIncrFn.
	incr incrFn
}

// incrFn is the dispatch shape for "increment one entry in one of the eight
// per-dimension sync.Maps". Either unboundedIncr (the upstream behavior, no
// cap) or a closure over boundedIncr (capped at a fixed entry count, with
// the lowest-frequency entries dropped first when the cap is exceeded).
type incrFn func(m *sync.Map, b *boundedCounter, key string)

func newIncrFn(maxEntries int) incrFn {
	if maxEntries <= 0 {
		return unboundedIncr
	}
	capN := maxEntries
	return func(m *sync.Map, b *boundedCounter, key string) {
		boundedIncr(m, b, key, capN)
	}
}

// unboundedIncr reproduces the maintainer's original Load → check → Store
// pattern verbatim. The bounded-counter sidecar parameter is ignored.
// Selected when CollectorOption.MaxEntriesPerStatMap == 0 (the default).
func unboundedIncr(m *sync.Map, _ *boundedCounter, key string) {
	v, ok := m.Load(key)
	if !ok {
		m.Store(key, 1)
	} else {
		m.Store(key, v.(int)+1)
	}
}

func NewStatisticCollector(option CollectorOption) (*Collector, error) {
	option.Database.NewTable("stats")

	//Create the collector object
	thisCollector := Collector{
		DailySummary: NewDailySummary(),
		Option:       &option,
		incr:         newIncrFn(option.MaxEntriesPerStatMap),
	}

	//Load the stat if exists for today
	//This will exists if the program was forcefully restarted
	year, month, day := time.Now().Date()
	summary := thisCollector.LoadSummaryOfDay(year, month, day)
	if summary != nil {
		thisCollector.DailySummary = summary
	}

	//Schedule the realtime statistic clearing at midnight everyday
	rtstatStopChan := thisCollector.ScheduleResetRealtimeStats()
	thisCollector.rtdataStopChan = rtstatStopChan

	return &thisCollector, nil
}

// Set the autosave duration, the collector will save the daily summary to database
// set saveInterval to 0 to disable autosave
func (c *Collector) SetAutoSave(saveInterval int) {
	//Stop the current ticker if exists
	if c.autSaveStop != nil {
		c.autSaveStop <- true
	}

	if saveInterval == 0 {
		return
	}

	c.autSaveStop = make(chan bool)
	ticker := time.NewTicker(time.Duration(saveInterval) * time.Second)
	c.autoSaveTicker = ticker

	go func() {
		for {
			select {
			case <-ticker.C:
				c.SaveSummaryOfDay()
			case <-c.autSaveStop:
				ticker.Stop()
				return
			}
		}
	}()
}

// Write the current in-memory summary to database file
func (c *Collector) SaveSummaryOfDay() {
	//When it is called in 0:00am, make sure it is stored as yesterday key
	t := time.Now().Add(-30 * time.Second)
	summaryKey := t.Format("2006_01_02")
	saveData := DailySummaryToExport(*c.DailySummary)
	c.Option.Database.Write("stats", summaryKey, saveData)
}

// Get the daily summary up until now
func (c *Collector) GetCurrentDailySummary() *DailySummary {
	return c.DailySummary
}

// Load the summary of a day given
func (c *Collector) LoadSummaryOfDay(year int, month time.Month, day int) *DailySummary {
	date := time.Date(year, time.Month(month), day, 0, 0, 0, 0, time.Local)
	summaryKey := date.Format("2006_01_02")
	targetSummaryExport := DailySummaryExport{}
	c.Option.Database.Read("stats", summaryKey, &targetSummaryExport)
	targetSummary := DailySummaryExportToSummary(targetSummaryExport)
	return &targetSummary
}

// Reset today summary, for debug or restoring injections
func (c *Collector) ResetSummaryOfDay() {
	c.DailySummary = NewDailySummary()
}

// This function gives the current slot in the 288- 5 minutes interval of the day
func (c *Collector) GetCurrentRealtimeStatIntervalId() int {
	now := time.Now()
	startOfDay := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.Local).Unix()
	secondsSinceStartOfDay := now.Unix() - startOfDay
	interval := secondsSinceStartOfDay / (5 * 60)
	return int(interval)
}

func (c *Collector) Close() {
	//Stop the ticker
	c.rtdataStopChan <- true

	//Write the buffered data into database
	c.SaveSummaryOfDay()
}

// Main function to record all the inbound traffics
// Note that this function run in go routine and might have concurrent R/W issue
// Please make sure there is no racing paramters in this function
func (c *Collector) RecordRequest(ri RequestInfo) {
	go func() {
		c.DailySummary.TotalRequest++
		if ri.Succ {
			c.DailySummary.ValidRequest++
		} else {
			c.DailySummary.ErrorRequest++
		}

		//Store the request info into correct types of maps. c.incr is
		//either the original upstream Load/Store pattern (unbounded) or
		//a capped variant that drops the lowest-count entries when
		//full. Selected once at startup based on the -stats_max_entries
		//flag (default 0 = unbounded).
		c.incr(c.DailySummary.ForwardTypes, c.DailySummary.bounded.ForwardTypes, ri.ForwardType)

		//Record the HTTP method of the request
		if ri.RequestMethod != "" {
			c.incr(c.DailySummary.RequestMethods, c.DailySummary.bounded.RequestMethods, ri.RequestMethod)
		}

		originISO := strings.ToLower(ri.RequestOriginalCountryISOCode)
		c.incr(c.DailySummary.RequestOrigin, c.DailySummary.bounded.RequestOrigin, originISO)

		//Filter out CF forwarded requests
		if strings.Contains(ri.IpAddr, ",") {
			ips := strings.Split(strings.TrimSpace(ri.IpAddr), ",")
			if len(ips) >= 1 && IsValidIPAddress(strings.TrimPrefix(ips[0], "[")) {
				//Example when forwarded from CF: 158.250.160.114,109.21.249.211
				//Or IPv6 [15c4:cbb4:cc98:4291:ffc1:3a46:06a1:51a7],109.21.249.211
				ri.IpAddr = ips[0]
			}
		}

		c.incr(c.DailySummary.RequestClientIp, c.DailySummary.bounded.RequestClientIp, ri.IpAddr)

		//Record the referer
		p := bluemonday.StripTagsPolicy()
		filteredReferer := p.Sanitize(
			ri.Referer,
		)
		c.incr(c.DailySummary.Referer, c.DailySummary.bounded.Referer, filteredReferer)

		//Record the UserAgent
		c.incr(c.DailySummary.UserAgent, c.DailySummary.bounded.UserAgent, ri.UserAgent)

		//Record request URL, if it is a page
		ext := filepath.Ext(ri.RequestURL)

		if ext != "" && !isWebPageExtension(ext) {
			return
		}

		c.incr(c.DailySummary.RequestURL, c.DailySummary.bounded.RequestURL, ri.RequestURL)

		//Record the downstream hostname
		//This is the hostname that the user visited, not the target domain
		c.incr(c.DailySummary.DownstreamHostnames, c.DailySummary.bounded.DownstreamHostnames, ri.Target)

		//Record the upstream hostname
		//This is the selected load balancer upstream hostname or ip
		c.incr(c.DailySummary.UpstreamHostnames, c.DailySummary.bounded.UpstreamHostnames, ri.Upstream)
	}()

	//ADD MORE HERE IF NEEDED
}

// nightly task
func (c *Collector) ScheduleResetRealtimeStats() chan bool {
	doneCh := make(chan bool)

	go func() {
		defer close(doneCh)

		for {
			// calculate duration until next midnight
			now := time.Now()

			// Get midnight of the next day in the local time zone
			midnight := time.Date(now.Year(), now.Month(), now.Day()+1, 0, 0, 0, 0, now.Location())

			// Calculate the duration until midnight
			duration := midnight.Sub(now)
			select {
			case <-time.After(duration):
				// store daily summary to database and reset summary
				c.SaveSummaryOfDay()
				c.DailySummary = NewDailySummary()
			case <-doneCh:
				// stop the routine
				return
			}
		}
	}()

	return doneCh
}

func NewDailySummary() *DailySummary {
	return &DailySummary{
		TotalRequest:        0,
		ErrorRequest:        0,
		ValidRequest:        0,
		ForwardTypes:        &sync.Map{},
		RequestOrigin:       &sync.Map{},
		RequestClientIp:     &sync.Map{},
		Referer:             &sync.Map{},
		UserAgent:           &sync.Map{},
		RequestURL:          &sync.Map{},
		RequestMethods:      &sync.Map{},
		DownstreamHostnames: &sync.Map{},
		UpstreamHostnames:   &sync.Map{},
		bounded:             newBoundedCounters(),
	}
}

func PrintDailySummary(summary *DailySummary) {
	summary.ForwardTypes.Range(func(key, value interface{}) bool {
		println(key.(string), value.(int))
		return true
	})
	summary.RequestOrigin.Range(func(key, value interface{}) bool {
		println(key.(string), value.(int))
		return true
	})
	summary.RequestClientIp.Range(func(key, value interface{}) bool {
		println(key.(string), value.(int))
		return true
	})
	summary.Referer.Range(func(key, value interface{}) bool {
		println(key.(string), value.(int))
		return true
	})
	summary.UserAgent.Range(func(key, value interface{}) bool {
		println(key.(string), value.(int))
		return true
	})
	summary.RequestURL.Range(func(key, value interface{}) bool {
		println(key.(string), value.(int))
		return true
	})
}
